--- #YAML:1.0
name:                     Labyrinth-PSGI
version:                  1.02
abstract:                 PSGI handler for Labyrinth
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                                       5.006
  CGI::Cookie:                                0
  CGI::PSGI:                                  0
  IO::File:                                   0
  Labyrinth:                                  0
  Labyrinth::Variables:                       0
recommends:
  Test::CPAN::Meta:                           0
  Test::CPAN::Meta::JSON:                     0
  Test::Pod:                                  1.00
  Test::Pod::Coverage:                        0.08
build_requires:
  Test::More:                                 0.70

provides:
  Labyrinth::PSGI:
    file:     lib/Labyrinth/PSGI.pm
    version:  1.02
  Labyrinth::Query::PSGI:
    file:     lib/Labyrinth/Query/PSGI.pm
    version:  1.02
  Labyrinth::Writer::Render::PSGI:
    file:     lib/Labyrinth/Writer/Render/PSGI.pm
    version:  1.02

no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Labyrinth-PSGI
  repository: http://github.com/barbie/labyrinth-psgi

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: The Hand of Barbie 1.0
